### ISSUE TITLE
Unhandled exception if client unexpectedly quits. 

### ISSUE THREAD

**Issue by Poidokoff** [elitedekkerz/spacegame#1]
Hiya. 

There's an unhandled exception if a connected client unexpectedly quits while the server is iterating through client inputs. I've included a patch against the current commit that includes a fix.

[fix_disconnect.patch](https://gist.github.com/Pelend/c3a77453bcf76fc663e1a646099a92fa)

**Comment by netl** [comment]
patch applied. thanks :)
